# https://setuptools.pypa.io/en/latest/userguide/quickstart.html

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ducks_docker_compose"
dynamic = ["version", "description"]

[project.scripts]
ddc = "ducks_docker_compose.ddc:main"
